Use compose v2
pimcore/skeleton pull request #108
Opened 2022-07-28 19:10 UTC by yariksheptykin

Upgrade to docker compose v2 in CI

2022-08-04 08:37 UTC, kingjia90 requested changes

2022-08-04 08:37 UTC, kingjia90 commented on .github/workflows/pimcore-skeleton.yml
> +        docker compose -v
it seems doesn't work with `-v`
```suggestion
        docker compose version
```
![image](https://user-images.githubusercontent.com/6014195/182801870-734f946a-5773-49d2-8dd0-756fc4dee49e.png)

2022-08-04 14:53 UTC, yariksheptykin commented on .github/workflows/pimcore-skeleton.yml
> +        docker compose -v
right you are. That schould be `compose version`. I'm on it.

2022-08-04 15:02 UTC, yariksheptykin commented on .github/workflows/pimcore-skeleton.yml
> +        docker compose -v
What's weird though is that pipeline was green. I'd expect it to fail with the same error as yours.

2022-08-04 15:11 UTC, kingjia90 commented on .github/workflows/pimcore-skeleton.yml
> +        docker compose -v
quite weird, can we verify if is going to stop on wrong docker config, what about something like this?
```
docker compose config
cd sample-project/
docker compose config -q
```
knowing that in the root folder there shoulnd't be any docker conf

2022-08-04 16:01 UTC, yariksheptykin commented on .github/workflows/pimcore-skeleton.yml
> +        docker compose -v
Good idea. I'll try that out

2022-08-05 12:05 UTC, yariksheptykin commented on .github/workflows/pimcore-skeleton.yml
> +        docker compose -v
@kingjia90 I've simulated some breakage, which this CI should definitely guard as against:
- [malformed YAML](https://github.com/pimcore/skeleton/pull/108/commits/accd512671302aca2d5db6b22840b5915f3c869a)
- [missing docker-compose.yml](https://github.com/pimcore/skeleton/runs/7690806435?check_suite_focus=true)

Both lead to pipeline halt, which is good.
That `-v` thing appears to be something related to how docker / compose is set up in github's action runners. For whatever reason running `docker compose -v` in this environment does not result in an error. Instead you get help output:
```
+ docker compose -v

Usage:  docker compose [OPTIONS] COMMAND

Docker Compose

Options:
      --ansi string                Control when to print ANSI control
                                   characters ("never"|"always"|"auto")
                                   (default "auto")
      --compatibility              Run compose in backward compatibility mode
      --env-file string            Specify an alternate environment file.
  -f, --file stringArray           Compose configuration files
      --profile stringArray        Specify a profile to enable
      --project-directory string   Specify an alternate working directory
                                   (default: the path of the, first
                                   specified, Compose file)
  -p, --project-name string        Project name
...
```
I first suspected that these Github VMs have compose-switch installed, which tries to provide a compatibility layer between compose v1 and v2. However the switch would translate [`-v` option to `version`](https://github.com/docker/compose-switch/blob/master/redirect/convert.go), which prints a different output. There is something different going on on that VM.

I don't think, though that trying to understand what exactly is going on there will help us much. As long as CI breaks on major bugs like we simulated, we should be safe.

I suggest we rewrite the history to get rid of those "debugging" commits and carry on with review / landing. What do you think?

2022-08-05 13:10 UTC, kingjia90 commented on .github/workflows/pimcore-skeleton.yml
> +        docker compose -v
Thank you for the detailed response!
Yes, i agree with you, knowing that it will stop on config error is enough.
The rest looks and works fine, so i will be merging it once you force pushed

2022-08-05 13:33 UTC, kingjia90 approved these changes

2022-08-05 13:38 UTC, merged