Draft: Add RabbitMQ to docker-compose.yaml (#186)
pimcore/skeleton pull request #187
Opened 2024-04-01 22:21 UTC by skoch98

Resolves #186

**ATTENTION** Do not merge this until https://github.com/pimcore/docker/pull/152 has been rolled out as a stable Docker image release!

You can test this PR by replaceing the `php` and `supervisord` image to the current dev version:
```diff
php:
-  image: pimcore/pimcore:php8.2-debug-latest
+  image: pimcore/pimcore:php8.2-debug-v3-dev
supervisord:
  image: pimcore/pimcore:php8.2-supervisord-latest
+  image: pimcore/pimcore:php8.2-supervisord-v3-dev
```

Run `watch -n 1 sudo docker compose exec rabbitmq rabbitmqctl list_queues` to monitor the current queue overview with the pending tasks. For example, upload images to see that `pimcore_asset_update` are being processed.

2024-04-01 22:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pimcore/skeleton?pullRequest=187) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pimcore/skeleton?pullRequest=187) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pimcore/skeleton?pullRequest=187) it.</sub>

2024-04-01 23:02 UTC, jdreesen commented on composer.json
> +    "symfony/amqp-messenger": "^5.4",
I think we should also use (at least) `^6.2` here.

2024-04-01 23:16 UTC, skoch98 commented on composer.json
> +    "symfony/amqp-messenger": "^5.4",
Thx, you're totally right. I fixed, tested & pushed it! :-)

2024-04-02 08:30 UTC, brusch requested changes

2024-04-02 08:30 UTC, brusch commented on .docker/messenger.yaml
> +            pimcore_core: '%env(MESSENGER_TRANSPORT_DSN)%pimcore_core'
```suggestion
            pimcore_core: 'amqp://rabbitmq:5672'
```
For me it would be fine to just have it hardcoded here ... keeps things a bit simpler 😊

2024-04-02 09:49 UTC, skoch98 commented on .docker/messenger.yaml
> +            pimcore_core: '%env(MESSENGER_TRANSPORT_DSN)%pimcore_core'
Changed to `amqp://rabbitmq:5672/%2f/pimcore_core` - so each queue is seperated:

```
$ docker compose exec rabbitmq rabbitmqctl list_queues
Timeout: 60.0 seconds ...
Listing queues for vhost / ...
name    messages
pimcore_maintenance     0
pimcore_image_optimize  0
pimcore_scheduled_tasks 0
pimcore_core    0
pimcore_asset_update    2
```

2024-04-02 10:09 UTC, brusch requested changes

2024-04-02 10:09 UTC, brusch commented on docker-compose.yaml
> +        image: rabbitmq:alpine
```suggestion
        image: rabbitmq:alpine
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq/
```
I think we should use persistence as the default.

2024-04-02 10:53 UTC, skoch98 commented on docker-compose.yaml
> +        image: rabbitmq:alpine
Done (but I used `pimcore-rabbitmq` instead to stay consistent). And it also works now with the latest docker prod image :+1:

2024-04-02 12:58 UTC, brusch approved these changes

2024-04-22 10:21 UTC, mcop1 commented
Since https://github.com/pimcore/docker/pull/152 was merged, the image was released and the pr was even approved already, I merged it.
Thanks everyone for creating/improving the pr :+1:

2024-04-22 10:21 UTC, merged