Add quill to bundleSetup
pimcore/skeleton pull request #217
Opened 2024-12-10 14:44 UTC by robertSt7

2024-12-10 15:12 UTC, mattamon approved these changes
LGTM!

2024-12-10 16:14 UTC, jdreesen commented
Shouldn't this have been included in the `2024.4` release?

2024-12-11 08:51 UTC, brusch commented
@jdreesen yeah, we missed that one, but for skeleton it's not that critical, since it's not getting updated for existing installation, because it's using `composer create-project` and there it's just using the latest release.

2024-12-12 11:40 UTC, brusch requested changes

2024-12-12 11:40 UTC, brusch commented on src/EventSubscriber/BundleSetupSubscriber.php
> +        $event->addInstallableBundle('PimcoreQuillBundle', PimcoreQuillBundle::class, true);
```suggestion
        $event->addRequiredBundle('PimcoreQuillBundle', PimcoreQuillBundle::class, true);
```

Should we make it a required bundle? 
Probably every developer expects to have a WYSIWYG when installing Pimcore, right? 🤔

2024-12-12 13:58 UTC, merged