Remove separate PHP debug container
pimcore/skeleton pull request #99
Opened 2022-06-24 18:28 UTC by jdreesen

I don't think it's necessary to have a separate debug container, as Xdebug supports this out of the box. You just have to start it on demand, instead of eagerly with every request. It should have a minimal overhead (in `v3`) when not enabled ([via cookie or env variable](https://xdebug.org/docs/step_debug#activate_debugger)).

2022-06-24 18:37 UTC, jdreesen commented on .docker/php-xdebug.ini
> +xdebug.start_with_request = default
This is only necessary because Pimcore's docker file starts Xdebug on every request. With pimcore/docker#95 this isn't necessary anymore.

2022-06-27 06:24 UTC, passioneight commented on docker-compose.yaml
> +        image: pimcore/pimcore:PHP8.1-fpm-debug
@jdreesen shouldn't it be possible to completely remove any overhead when adding this change (including the added volume) to the `docker-compose.override.yaml`?

By default (e.g., for local development) `docker-compose up -d` will merge the config files and we'd be able to debug as you stated. For other environments (like `prod`), one could add the `-f docker-compose.yaml` option to avoid the merge and therefore have zero overhead. Yet, if you need the debugger for another environment, you can still skip the `-f` option.

Wdyt?

2022-06-27 07:39 UTC, brusch commented
What about performance? As far as I can remember, the `-debug` images were horribly slow, especially on windows environments. Or is using `xdebug.start_with_request = default` making that better?

2022-06-27 07:42 UTC, jdreesen commented on docker-compose.yaml
> +        image: pimcore/pimcore:PHP8.1-fpm-debug
Sure, for `prod` that would remove any overhead and would be the next step.

2022-06-27 07:52 UTC, jdreesen commented
Yes, that setting should make it better, as Xdebug is only activated on demand (via cookie (web) or env variable (cli)), just like you did manually here. Xdebug v3 greatly optimized this in comparison to earlier versions, see: https://php.watch/articles/xdebug2-vs-3-benchmark

2022-07-27 14:44 UTC, yariksheptykin commented on docker-compose.yaml
> +        image: pimcore/pimcore:PHP8.1-fpm-debug
@passioneight you might not want to use this `docker-compose.yml` in production. It does not provide replication, cron-jobs are not properly set up, webserver does not use HTTPS. These are some examples of the issues with this compose file, which make it not quite ready for production. docker compose itself as compared to kubernetes or other cloud solutions might not be the best option for running containers in production.

I'd suggest to focus this docker compose file on running pimcore locally during development. If we nail this use-case, make pimcore development to be fast, fun, with major dev tools installed out-of-the-box, it would be a great step forward. It does not mean we should completely ignore how pimcore runs in production. I just think we should not try to build a docker-compose.yml, which could be used to run pimcore in production.

2022-07-30 19:25 UTC, passioneight commented on docker-compose.yaml
> +        image: pimcore/pimcore:PHP8.1-fpm-debug
I agree, running Pimcore locally surely should be the main focus. Additionally, I wouldn't run this docker-compose file in production either. 

Still, I think it wouldn't hurt to split the files as it adds more flexibility, while still being able to add any required tools just as easily.

2022-10-10 14:27 UTC, jdreesen commented
Now that pimcore/docker#104 is merged, this one could be merged, too, as the separate debug container isn't necessary anymore.

2022-10-13 09:24 UTC, brusch requested changes

2022-10-13 09:24 UTC, brusch commented on docker-compose.yaml
> -            - pimcore-tmp-storage:/tmp
Why removing the /tmp volumne as well?

2022-10-13 09:26 UTC, brusch commented
Reminder: we need to do this for pimcore/demo as well.

2022-10-13 09:31 UTC, jdreesen commented on docker-compose.yaml
> -            - pimcore-tmp-storage:/tmp
Do we still need this? As far as I understood it, it was only used to synchronize sessions between containers. Is it used for anything else?

2022-10-13 09:32 UTC, brusch commented on docker-compose.yaml
> -            - pimcore-tmp-storage:/tmp
Ah, yes, you're right! That was at least one of the reasons 😊 Let's try it without and see if we experience any issues.

2022-10-13 13:56 UTC, merged